/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 *
 * Settings writer for VSCode extension.
 * Handles bidirectional sync between VSCode Settings and ~/.o1-code/settings.json.
 */

import { logger } from '../utils/logger.js';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  ALL_PROVIDERS,
  AuthType,
  Storage,
  applyProviderInstallPlan,
  preserveModelProviderPlaceholders,
  type ProviderProtocolConfig,
  resolveMetadataKey,
  stripRuntimeSnapshotPrefix,
  type ProviderInstallPlan,
  type ProviderSettingsAdapter,
  type ModelProvidersConfig,
} from '@organizaone/o1-code-core';
import { resolveEnvVarsInObject } from '@organizaone/o1-code-core/envVarResolver';
import {
  listCredentials,
  readCredential,
  removeCredential,
  writeCredential,
} from '@organizaone/o1-code-core/providers/credential-store.js';
import { resolveModelApiKey } from '@organizaone/o1-code-core/providers/model-api-key.js';
import {
  CodingPlanRegion,
  SUBSCRIPTION_PLAN_OPTIONS,
  findSubscriptionPlanByConfig,
  getSubscriptionPlanConfig,
  isSubscriptionPlanConfig,
} from './subscriptionPlanDefinitions.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Mode for ~/.o1-code/settings.json — owner-only read/write. Keys live in the
 * credential store, but the file can still hold header values and endpoints
 * a user would not share. Keep this in sync with `loadedSettingsAdapter`.
 */
const SETTINGS_FILE_MODE = 0o600;

/** Credential id the api-key flow saves its OpenAI-compatible key under. */
const OPENAI_CREDENTIAL_ID = 'openai';

/** Credential id of a subscription plan: its preset id (`coding-plan`, …). */
function planCredentialId(plan: { id: string }): string {
  return `${plan.id}-plan`;
}
/** Directory mode for ~/.o1-code — owner-only. */
const SETTINGS_DIR_MODE = 0o700;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Model providers as key-value map: modelId → baseUrl.
 * This is the format VSCode Settings UI can render as an editable table.
 */
export type VSCodeModelProviders = Record<string, string>;

/**
 * Values extracted from ~/.o1-code/settings.json for populating VSCode Settings.
 */
export interface O1CodeSettingsForVSCode {
  provider: 'coding-plan' | 'api-key';
  apiKey: string;
  codingPlanRegion: 'china' | 'global';
}

// ---------------------------------------------------------------------------
// Low-level read/write helpers
// ---------------------------------------------------------------------------

/**
 * Length of a JSON escape sequence starting with `\\`. Handles the six-char
 * `\\uXXXX` form — otherwise a value like `"sk-abc\\u0022,..."` would let the
 * embedded `\\u0022` close the string early and the rest of the buffer would
 * parse as additional keys, enabling settings.json key injection.
 */
function jsonEscapeLength(text: string, backslashIdx: number): number {
  return text[backslashIdx + 1] === 'u' ? 6 : 2;
}

/**
 * Strip single-line (`//`) and multi-line comments from JSONC content
 * so that `JSON.parse` can handle ~/.o1-code/settings.json files that
 * contain comments (common when hand-edited or generated by CLI).
 */
function stripJsonComments(text: string): string {
  let result = '';
  let i = 0;
  while (i < text.length) {
    // String literal — copy verbatim (handles escaped quotes)
    if (text[i] === '"') {
      let j = i + 1;
      while (j < text.length) {
        if (text[j] === '\\') {
          j += jsonEscapeLength(text, j);
        } else if (text[j] === '"') {
          j++;
          break;
        } else {
          j++;
        }
      }
      result += text.slice(i, j);
      i = j;
    } else if (text[i] === '/' && text[i + 1] === '/') {
      // Single-line comment — skip until newline
      const nl = text.indexOf('\n', i);
      i = nl === -1 ? text.length : nl;
    } else if (text[i] === '/' && text[i + 1] === '*') {
      // Multi-line comment — skip until */
      const end = text.indexOf('*/', i + 2);
      i = end === -1 ? text.length : end + 2;
    } else {
      result += text[i];
      i++;
    }
  }
  return result;
}

/**
 * Strip trailing commas inside arrays/objects (`,]` / `,}`) — VSCode's own
 * settings.json allows them and they crash strict JSON.parse. Uses a
 * character-by-character scanner so that the `,]` substring inside a string
 * literal (e.g. `"MY_VAR": ",]"`) is preserved unchanged — a regex would
 * silently rewrite it and corrupt the value.
 */
function stripTrailingCommas(text: string): string {
  let result = '';
  let i = 0;
  while (i < text.length) {
    const ch = text[i];
    if (ch === '"') {
      // Copy the entire string literal (including escapes) verbatim. Must
      // use the same jsonEscapeLength helper as stripJsonComments so that
      // `"` is not mis-parsed as `\u` + early-terminating `"`.
      let j = i + 1;
      while (j < text.length) {
        if (text[j] === '\\') {
          j += jsonEscapeLength(text, j);
          continue;
        }
        if (text[j] === '"') {
          j++;
          break;
        }
        j++;
      }
      result += text.slice(i, j);
      i = j;
      continue;
    }
    if (ch === ',') {
      // Drop comma only if the next non-whitespace char is } or ].
      let j = i + 1;
      while (j < text.length && /\s/.test(text[j]!)) j++;
      if (j < text.length && (text[j] === ']' || text[j] === '}')) {
        i++;
        continue;
      }
    }
    result += ch;
    i++;
  }
  return result;
}

/**
 * Read ~/.o1-code/settings.json. Returns {} if the file is missing.
 * Parse errors are logged and re-thrown so callers don't silently destroy a
 * malformed file by treating it as empty and then overwriting it.
 * Handles JSONC (JSON with comments + trailing commas) for hand-edited files.
 */
function readSettings(): Record<string, unknown> {
  const settingsPath = Storage.getGlobalSettingsPath();
  let content: string;
  try {
    content = fs.readFileSync(settingsPath, 'utf-8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      return {};
    }
    throw err;
  }
  try {
    return JSON.parse(
      stripTrailingCommas(stripJsonComments(content)),
    ) as Record<string, unknown>;
  } catch (err) {
    // Surface an actionable message rather than the raw SyntaxError. The
    // caller's catch will see this; refusing to overwrite a malformed file
    // is the whole point — better than silently destroying user state by
    // treating it as `{}`.
    logger.error(
      `[settingsWriter] Failed to parse ${settingsPath}; refusing to overwrite a malformed file.`,
      err,
    );
    const message =
      err instanceof Error ? `${err.name}: ${err.message}` : String(err);
    throw new Error(
      `Cannot parse ~/.o1-code/settings.json (${message}). ` +
        `Standard JSONC (// comments, /* */, trailing commas) is supported, ` +
        `but non-standard JSON features (unquoted keys, single quotes) are not. ` +
        `Please fix or delete ${settingsPath} and try again.`,
      { cause: err instanceof Error ? err : undefined },
    );
  }
}

/**
 * Write ~/.o1-code/settings.json atomically (temp file + rename), creating the
 * directory if needed. Atomic rename prevents leaving a half-written file
 * behind on EACCES / disk-full / process crash mid-write.
 */
function writeSettings(settings: Record<string, unknown>): void {
  const settingsPath = Storage.getGlobalSettingsPath();
  const dir = path.dirname(settingsPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: SETTINGS_DIR_MODE });
  }
  const tmpPath = `${settingsPath}.${process.pid}.${Date.now()}.tmp`;
  // Create the temp file with owner-only permissions so secrets in `env.*`
  // are never observable to other local users even briefly.
  fs.writeFileSync(tmpPath, JSON.stringify(settings, null, 2), {
    encoding: 'utf-8',
    mode: SETTINGS_FILE_MODE,
  });
  try {
    fs.renameSync(tmpPath, settingsPath);
  } catch (renameErr) {
    // renameSync can fail on Windows when a watcher / antivirus holds the
    // target (EPERM/EBUSY). The temp file otherwise lingers in ~/.o1-code
    // containing API keys — clean it up so secrets don't accumulate on
    // disk across repeated failed writes.
    try {
      fs.unlinkSync(tmpPath);
    } catch {
      /* best-effort cleanup; surface the original rename error below */
    }
    throw renameErr;
  }
  // Tighten any pre-existing settings file inherited from older writes that
  // used the default umask. chmodSync is a no-op on the just-written file but
  // covers the case where the file was created earlier with looser bits.
  try {
    fs.chmodSync(settingsPath, SETTINGS_FILE_MODE);
  } catch {
    // Best effort — surface nothing to the user if the FS rejects chmod
    // (e.g. Windows, mounted FS without POSIX permissions).
  }
}

/**
 * Ensure nested objects exist at the given key path.
 */
function ensureNestedObject(
  obj: Record<string, unknown>,
  ...keys: string[]
): Record<string, unknown> {
  let current = obj;
  for (const key of keys) {
    if (!current[key] || typeof current[key] !== 'object') {
      current[key] = {};
    }
    current = current[key] as Record<string, unknown>;
  }
  return current;
}

/**
 * Find OpenAI-compatible model entries from modelProviders.
 * CLI uses AuthType.USE_OPENAI ('openai') as the key, but some legacy
 * configs may use other keys. Check both.
 */
function findOpenaiModels(
  modelProviders: Record<string, unknown> | undefined,
): Array<Record<string, unknown>> {
  if (!modelProviders) {
    return [];
  }
  for (const key of [AuthType.USE_OPENAI, 'use_openai']) {
    const entry = modelProviders[key];
    // V4 shape: the provider value is a ModelConfig[] array.
    if (Array.isArray(entry) && entry.length > 0) {
      return entry as Array<Record<string, unknown>>;
    }
    // Read-side tolerance for a settings file still in the reverted V5
    // shape ({ protocol, models }) that the CLI v5->v4 migration has not yet
    // rewritten — the extension reads/writes settings.json without running
    // that migration. The extension still writes V4 arrays; this only needs to
    // avoid dropping existing entries when reading a not-yet-downgraded file.
    if (typeof entry === 'object' && entry !== null && !Array.isArray(entry)) {
      const models = (entry as Record<string, unknown>)['models'];
      if (Array.isArray(models) && models.length > 0) {
        return models as Array<Record<string, unknown>>;
      }
    }
  }
  return [];
}

// ---------------------------------------------------------------------------
// Write: VSCode Settings → ~/.o1-code/settings.json
// ---------------------------------------------------------------------------

/**
 * Write Coding Plan configuration to ~/.o1-code/settings.json.
 * Auto-injects model providers from the regional template,
 * preserving any existing non-Coding-Plan entries.
 *
 * @returns The injected models as a VSCode key-value map (modelId → baseUrl)
 */
export function writeCodingPlanConfig(
  region: 'china' | 'global',
  apiKey: string,
): VSCodeModelProviders {
  const settings = readSettings();
  const codingRegion =
    region === 'global' ? CodingPlanRegion.GLOBAL : CodingPlanRegion.CHINA;
  const planConfig = getSubscriptionPlanConfig('coding', codingRegion);

  // Auth
  const auth = ensureNestedObject(settings, 'security', 'auth');
  auth.selectedType = AuthType.USE_OPENAI;

  // API key: saved in the credential store, named by the model entries.
  const credential = planCredentialId(planConfig);
  writeCredential(credential, { apiKey });

  // Model providers — merge Coding Plan templates with existing non-CP entries
  const providers = ensureNestedObject(settings, 'modelProviders');
  const existing = findOpenaiModels(
    settings.modelProviders as Record<string, unknown>,
  );
  const nonCodingPlan = existing.filter(
    (e) => !isSubscriptionPlanConfig(e.baseUrl as string, e.envKey as string),
  );
  const planModels = planConfig.template.map((model) => ({
    ...model,
    envKey: planConfig.envKey,
    credential,
  }));
  providers[AuthType.USE_OPENAI] = [...planModels, ...nonCodingPlan];

  // Coding Plan metadata — write to the providerMetadata namespace that
  // the CLI now reads from. Remove legacy top-level key if present.
  const providerMetadata = ensureNestedObject(settings, 'providerMetadata');
  providerMetadata['coding-plan'] = {
    region: codingRegion,
    baseUrl: planConfig.baseUrl,
    version: planConfig.version,
  };
  delete settings.codingPlan;

  // Default model
  const defaultModelId = planConfig.template[0]?.id ?? 'qwen3.5-plus';
  settings.model = { name: defaultModelId };

  writeSettings(settings);

  // Return key-value map for VSCode settings
  const result: VSCodeModelProviders = {};
  for (const m of planConfig.template) {
    result[m.id] = m.baseUrl || '';
  }
  return result;
}

/**
 * Write model providers from VSCode Settings (key-value map) to ~/.o1-code/settings.json.
 * Used when provider = "api-key" and user edits the modelProviders map.
 *
 * @param params.apiKey - The API key
 * @param params.modelProviders - Map of modelId → baseUrl
 * @param params.activeModel - Currently selected model ID
 */
export function writeModelProvidersConfig(params: {
  apiKey: string;
  modelProviders: VSCodeModelProviders;
  activeModel: string;
}): void {
  const settings = readSettings();

  // Auth
  const auth = ensureNestedObject(settings, 'security', 'auth');
  auth.selectedType = AuthType.USE_OPENAI;

  // API key: saved in the credential store; the subscription plans' keys are
  // forgotten, since their entries no longer drive the selection.
  writeCredential(OPENAI_CREDENTIAL_ID, { apiKey: params.apiKey });
  for (const plan of SUBSCRIPTION_PLAN_OPTIONS) {
    removeCredential(planCredentialId(plan));
  }

  // Convert key-value map to CLI's array format and merge with existing
  // non-target entries so reconfiguring one provider doesn't silently
  // delete others (e.g. Coding Plan entries with a different envKey).
  const providers = ensureNestedObject(settings, 'modelProviders');
  const modelArray = Object.entries(params.modelProviders).map(
    ([id, baseUrl]) => ({
      id,
      name: id,
      baseUrl: baseUrl || 'https://api.openai.com/v1',
      envKey: 'OPENAI_API_KEY',
      credential: OPENAI_CREDENTIAL_ID,
    }),
  );
  const existing = findOpenaiModels(
    settings.modelProviders as Record<string, unknown>,
  );
  const nonTarget = existing.filter((e) => e.envKey !== 'OPENAI_API_KEY');
  providers[AuthType.USE_OPENAI] = [...modelArray, ...nonTarget];

  // Active model
  if (params.activeModel) {
    settings.model = { name: params.activeModel };
  }

  for (const plan of SUBSCRIPTION_PLAN_OPTIONS) {
    delete settings[plan.metadataKey];
  }
  const pm = settings.providerMetadata as Record<string, unknown> | undefined;
  if (pm) {
    delete pm['coding-plan'];
    delete pm['token-plan'];
  }

  writeSettings(settings);
}

// ---------------------------------------------------------------------------
// Unified install plan — bridges core's ProviderInstallPlan to file I/O
// ---------------------------------------------------------------------------

/**
 * Create a ProviderSettingsAdapter backed by ~/.o1-code/settings.json.
 * Reads/writes use the low-level helpers already in this module.
 */
export function resolveProviderSettings(
  settings: Record<string, unknown>,
): Record<string, unknown> {
  const storedEnv = settings['env'];
  const env = Object.fromEntries(
    Object.entries({
      ...(storedEnv &&
      typeof storedEnv === 'object' &&
      !Array.isArray(storedEnv)
        ? storedEnv
        : {}),
      ...process.env,
    }).filter(
      (entry): entry is [string, string] => typeof entry[1] === 'string',
    ),
  );
  return resolveEnvVarsInObject(settings, env);
}

function createFileSettingsAdapter(): ProviderSettingsAdapter {
  let data = readSettings();
  const originalProviders = structuredClone(
    data['modelProviders'] ?? {},
  ) as ModelProvidersConfig;
  const resolvedProviders =
    (resolveProviderSettings(data)['modelProviders'] as ModelProvidersConfig) ??
    {};
  let writeProviders: ModelProvidersConfig = {};
  let rawWriteProviders: ModelProvidersConfig = {};
  let backupData: Record<string, unknown> | null = null;

  return {
    getValue(key: string): unknown {
      const parts = key.split('.');
      let current: unknown = resolveProviderSettings(data);
      for (const part of parts) {
        if (current == null || typeof current !== 'object') return undefined;
        current = (current as Record<string, unknown>)[part];
      }
      return current;
    },

    setValue(key: string, value: unknown): void {
      if (
        key.startsWith('modelProviders.') &&
        key.split('.').length === 2 &&
        Array.isArray(value)
      ) {
        const provider = key.slice('modelProviders.'.length);
        // Pruning filters the latest write view; install patches instead carry
        // models resolved before env rotation. Compare against their own view.
        const fromWriteView = value.every((model) =>
          writeProviders[provider]?.includes(model),
        );
        value = preserveModelProviderPlaceholders(
          value,
          provider,
          fromWriteView ? writeProviders : resolvedProviders,
          fromWriteView ? rawWriteProviders : originalProviders,
          resolveProviderSettings(data)['providerProtocol'] as
            | ProviderProtocolConfig
            | undefined,
        );
      }
      // Never persist a runtime snapshot ID to model.name (it re-wraps on restart).
      if (key === 'model.name' && typeof value === 'string') {
        value = stripRuntimeSnapshotPrefix(value);
      }
      const parts = key.split('.');
      let current = data;
      for (let i = 0; i < parts.length; i++) {
        const part = parts[i]!;
        // Refuse to walk through prototype-pollution keys. ProviderInstallPlan
        // contents come from in-process callers, but install plans accept
        // arbitrary string keys (env vars, providerState namespaces) so the
        // input is untrusted enough to warrant the guard. Literal === checks
        // (not Set.has) are what CodeQL's prototype-pollution sanitiser
        // recognises — keep them at the only step that actually writes to
        // `current`.
        if (
          part === '__proto__' ||
          part === 'constructor' ||
          part === 'prototype'
        ) {
          throw new Error(
            `Refusing to write settings key with reserved segment: ${key}`,
          );
        }
        if (i === parts.length - 1) {
          current[part] = value;
          break;
        }
        const existing = Object.prototype.hasOwnProperty.call(current, part)
          ? current[part]
          : undefined;
        if (existing == null) {
          current[part] = {};
        } else if (Array.isArray(existing) || typeof existing !== 'object') {
          // Refuse to silently overwrite a scalar (or treat an array as an
          // object) at an intermediate segment — would either destroy user
          // data (e.g. {"env": "legacy-string"} losing the string when
          // env.NEW_KEY is written) or set string keys on an array.
          throw new Error(
            `Cannot write settings key "${key}": segment "${part}" is ${
              Array.isArray(existing) ? 'an array' : `a ${typeof existing}`
            }, not an object`,
          );
        }
        current = current[part] as Record<string, unknown>;
      }
    },

    getModelProviders(): ModelProvidersConfig {
      return (resolveProviderSettings(data)['modelProviders'] ??
        {}) as ModelProvidersConfig;
    },

    getModelProvidersForWrite() {
      const resolved = resolveProviderSettings(data);
      writeProviders = (resolved['modelProviders'] ??
        {}) as ModelProvidersConfig;
      rawWriteProviders = structuredClone(
        data['modelProviders'] ?? {},
      ) as ModelProvidersConfig;
      return {
        modelProviders: writeProviders,
        providerProtocol: resolved['providerProtocol'] as
          | ProviderProtocolConfig
          | undefined,
        shadowedProviders: [],
      };
    },

    persist(): void {
      writeSettings(data);
    },

    backup(): void {
      backupData = JSON.parse(JSON.stringify(data)) as Record<string, unknown>;
    },

    restore(): void {
      if (!backupData) return;
      // Write to disk FIRST. If writeSettings throws (EACCES / disk full /
      // EPERM on Windows), the in-memory update is skipped on purpose:
      // callers never observe a clean snapshot while the file on disk lies.
      //
      // Note: the CLI adapter (loadedSettingsAdapter) takes a different
      // trade-off — restoreSettingsFromBackup() returns a boolean, so it
      // logs on failure and *unconditionally* restores in-memory state.
      // VS Code can be stricter because its writeSettings is the only path
      // and a throw here is recoverable; the CLI lacks that escape hatch.
      writeSettings(backupData);
      data = backupData;
      backupData = null;
    },

    cleanupBackup(): void {
      backupData = null;
    },
  };
}

/**
 * Apply a ProviderInstallPlan to ~/.o1-code/settings.json.
 * This is the primary entry point for the VSCode interactive auth flow.
 *
 * `applyProviderInstallPlan` is async, so a returned (or thrown) Promise must
 * be awaited — otherwise an `EACCES` from `persist()` or the prototype-pollution
 * guard in `setValue()` would be swallowed and the caller would carry on
 * reconnecting the agent as if the settings write had succeeded.
 */
export async function applyProviderInstallPlanToFile(
  plan: ProviderInstallPlan,
): Promise<void> {
  const settings = createFileSettingsAdapter();
  await applyProviderInstallPlan(plan, { settings });
}

/**
 * Capture a deep-cloned snapshot of the current on-disk settings for rollback,
 * or `null` if the file is missing/unreadable.
 *
 * Unlike `readSettings`, this never throws — callers use it to checkpoint
 * before `applyProviderInstallPlanToFile` so that a *later* step the install
 * plan can't see (e.g. the agent reconnect rejecting a bad API key) can be
 * undone via {@link restoreSettingsSnapshot}. `applyProviderInstallPlan`'s own
 * backup/restore only covers failures *inside* the plan; the
 * disconnect/reconnect in WebViewProvider runs after `cleanupBackup`, so the
 * caller owns that rollback window.
 */
export function snapshotSettingsForRollback(): Record<string, unknown> | null {
  try {
    return structuredClone(readSettings());
  } catch (err) {
    // Leave a breadcrumb: returning null disables credential rollback, so if
    // settings are transiently unreadable (AV lock, disk hiccup) the oncall
    // engineer can tie repeated cross-restart auth failures back to here.
    // Log only the error's class name (not its message) — consistent with the
    // providerMatchesCredentials guard, so the security stance holds even
    // though this catch is filesystem errors rather than user-defined fns.
    logger.warn(
      '[settingsWriter] snapshotSettingsForRollback failed; credential rollback disabled:',
      err instanceof Error ? err.constructor.name : typeof err,
    );
    return null;
  }
}

/**
 * Write a snapshot captured by {@link snapshotSettingsForRollback} back to
 * disk. No-op when the snapshot is `null` (nothing safe to restore).
 */
/** The saved key an install is about to replace, for a rollback. */
export interface CredentialSnapshot {
  id: string;
  apiKey?: string;
}

export function snapshotCredential(id: string): CredentialSnapshot {
  const saved = readCredential(id);
  return saved ? { id, apiKey: saved.apiKey } : { id };
}

/** Puts back the saved key of a snapshot, or removes one that was not there. */
export function restoreCredential(snapshot: CredentialSnapshot | null): void {
  if (!snapshot) return;
  if (snapshot.apiKey) {
    writeCredential(snapshot.id, { apiKey: snapshot.apiKey });
  } else {
    removeCredential(snapshot.id);
  }
}

export function restoreSettingsSnapshot(
  snapshot: Record<string, unknown> | null,
): void {
  if (snapshot === null) return;
  writeSettings(snapshot);
}

// ---------------------------------------------------------------------------
// Read: ~/.o1-code/settings.json → VSCode Settings
// ---------------------------------------------------------------------------

/**
 * Read ~/.o1-code/settings.json and extract values for VSCode Settings UI.
 * Returns null if no valid configuration found, or if the file is
 * malformed — the panel falls back to the empty/default state instead of
 * crashing the extension on activation. `readSettings` itself now throws
 * on parse failure (so we never silently overwrite a corrupt file in the
 * write paths), so this caller has to catch.
 */
export function readO1CodeSettingsForVSCode(): O1CodeSettingsForVSCode | null {
  let settings: Record<string, unknown>;
  try {
    settings = readSettings();
  } catch (error) {
    logger.error(
      '[settingsWriter] readO1CodeSettingsForVSCode failed; returning null:',
      error,
    );
    return null;
  }

  const security = settings.security as Record<string, unknown> | undefined;
  const auth = security?.auth as Record<string, unknown> | undefined;
  if (!auth?.selectedType) {
    return null;
  }

  const modelProviders = settings.modelProviders as
    | Record<string, unknown>
    | undefined;
  const openaiModels = findOpenaiModels(modelProviders);
  // A model's key: its variable in the environment, then the saved
  // credential it names, then the credential of its preset.
  const keyOf = (model: Record<string, unknown> | undefined) =>
    resolveModelApiKey({
      envKey: (model?.envKey as string | undefined) || 'OPENAI_API_KEY',
      credential: model?.credential as string | undefined,
      baseUrl: model?.baseUrl as string | undefined,
    }) ?? '';
  const subscription = openaiModels
    .map((model) => ({
      model,
      match: findSubscriptionPlanByConfig(
        model.baseUrl as string | undefined,
        model.envKey as string | undefined,
      ),
    }))
    .find(({ model, match }) => match !== undefined && !!keyOf(model));
  const subscriptionPlan = subscription?.match;

  if (subscriptionPlan?.plan.id === 'coding') {
    const region = subscriptionPlan.region === 'global' ? 'global' : 'china';
    return {
      provider: 'coding-plan',
      apiKey: keyOf(subscription?.model),
      codingPlanRegion: region,
    };
  }

  // Non-Coding-Plan — find API key from model providers
  const apiKey = keyOf(openaiModels[0]);

  if (!apiKey) {
    return null;
  }

  return {
    provider: 'api-key',
    apiKey,
    codingPlanRegion: 'china',
  };
}

/**
 * Clear persisted auth: every saved key in the credential store, plus the
 * auth type selection and plan metadata in ~/.o1-code/settings.json, so
 * runtime state matches the cleared VS Code settings.
 */
export function clearPersistedAuth(): void {
  try {
    for (const id of listCredentials()) removeCredential(id);
  } catch (error) {
    logger.error('[settingsWriter] Failed to remove saved keys:', error);
  }
  try {
    const settings = readSettings();

    // Remove auth type selection
    const security = settings.security as Record<string, unknown> | undefined;
    if (security?.auth) {
      delete (security.auth as Record<string, unknown>).selectedType;
    }

    // Remove subscription plan metadata (legacy + new namespace)
    for (const plan of SUBSCRIPTION_PLAN_OPTIONS) {
      delete settings[plan.metadataKey];
    }
    const pm = settings.providerMetadata as Record<string, unknown> | undefined;
    if (pm) {
      // Every preset with a static models[] writes providerMetadata.<id>.version
      // via resolveProviderState — wipe them all on clear so stale entries
      // don't cause phantom "update available" notifications for a provider
      // the user just signed out of. resolveMetadataKey throws when a future
      // provider has '.' in its id; wrap per-iteration so one bad entry
      // can't abort the whole cleanup and leave secrets on disk.
      for (const p of ALL_PROVIDERS) {
        try {
          const key = resolveMetadataKey(p);
          if (key) delete pm[key];
        } catch {
          /* skip metadata cleanup for a misconfigured provider id */
        }
      }
    }

    writeSettings(settings);
  } catch (error) {
    logger.error(
      '[settingsWriter] Failed to clear persisted auth credentials:',
      error,
    );
  }
}
