#!/usr/bin/env node
/**
 * @license
 * Copyright 2026 o1-code contributors
 * SPDX-License-Identifier: Apache-2.0
 */

// Writes the brand module for the CLI and for core from brand.json, so each
// package reads its identity at run time without importing a file outside it.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
);
const FIELDS = [
  'productName',
  'displayName',
  'organization',
  'repoUrl',
  'coAuthorEmail',
];

export const BRAND_MODULE_TARGETS = ['cli', 'core'].map((pkg) =>
  path.join('packages', pkg, 'src', 'generated', 'brand.ts'),
);

export function renderBrandModule(identity) {
  const entries = FIELDS.map((field) => {
    const value = identity[field];
    if (typeof value !== 'string' || value === '') {
      throw new Error(`brand.json: identity.${field} is missing`);
    }
    return `  ${field}: ${JSON.stringify(value)},`;
  });
  return [
    '/**',
    ' * @license',
    ' * Copyright 2026 o1-code contributors',
    ' * SPDX-License-Identifier: Apache-2.0',
    ' */',
    '',
    '// Generated by scripts/o1/generate-brand.mjs from brand.json. Do not edit.',
    'export const BRAND = {',
    ...entries,
    '} as const;',
    '',
  ].join('\n');
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const brand = JSON.parse(readFileSync(path.join(root, 'brand.json'), 'utf8'));
  const source = renderBrandModule(brand.identity);
  for (const target of BRAND_MODULE_TARGETS) {
    const out = path.join(root, target);
    mkdirSync(path.dirname(out), { recursive: true });
    writeFileSync(out, source);
    console.log(`Generated ${target}`);
  }
}
